# Generated by Django 5.0.6 on 2024-05-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='book_author',
        ),
    ]
